version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - spring
  spring:
    container_name: spring
    image: brighto8z/talken-spring
    expose:
      - 8080
    ports:
      - 8080:8080
